version: "2.2"
services:

  app:
    image: "amirlaroussi/achat-1.0.jar"
    build: ./
    ports:
      - "8082:8082"
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/achatdb?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    depends_on:
      - mysqldb
    volumes:
      - .m2:/root/.m2


  mysqldb:
    image: "mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=achatdb
    ports:
      - "3306:3306"